#!/usr/bin/python

import openai
import readline # hooks into input()
from rich.console import Console
from rich.markdown import Markdown

if __name__ == '__main__':
    console = Console()
    messages = [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
    ]

    while True:
        request = input('Q: ')
        messages.append({"role": "user", "content": request})
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=messages,
        )
        assistant_message = response.choices[0]['message'] # type: ignore
        console.print(Markdown(assistant_message['content']))
        messages.append(assistant_message)
